apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/isaiahwong/dunamis
deploy:
  kubectl:
    manifests:
    - k8s/env.yaml
    - k8s/mail.yaml
    - k8s/secrets.yaml
