apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    resourceType: api-service
  annotations:
    config: '{
      "expose": true,
      "serviceType": "resource",
      "path": "payment",
      "apiVersion": "v1",
      "authentication": {
        "required": "true",
        "exclude": [
          "/api/v1/payment/stripe/webhook/paymentintent",
          "/api/v1/payment/stripe/webhook/test",
          "/api/v1/payment/paypal/webhook/test"
        ]
      }
    }'

spec:
  type: ClusterIP
  selector: 
    app: payment
  ports:
  - name: grpc
    port: 50051
    targetPort: grpc-port
  # - name: http
  #   port: 5000
  #   targetPort: http-port

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: payment
        image: registry.gitlab.com/isaiahwong/cluster/api/payment
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc-port
          containerPort: 50051
        # - name: http-port
        #   containerPort: 5000
        envFrom:
        - configMapRef:
            name: payment-env-configmap
        - secretRef:
            name: payment-env-secrets
        - secretRef:
            name: mongo-payment-env-secrets